title: Streamdata Gallery Google Spectrum Database
url: google-spectrum-database.streamdata.gallery
tag: Google Spectrum Database
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
github_user: streamdata-gallery
github_repo: google-spectrum-database
github_branch: master
collections:
  listings:
    output: true
    permalink: /listings/:path/
defaults:
  - scope:
      type: listings
    values:
      layout: listings
